AllCops:
  NewCops: enable

Naming/FileName:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
